//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionPartySetting
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string FirstNameActionParty { get; set; }
        public string LastNameActionParty { get; set; }
        public string EmailActionParty { get; set; }
        public string PhoneNumberActionParty { get; set; }
        public string JobTitleActionParty { get; set; }
    }
}
