//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratorScheduler
    {
        public int Id { get; set; }
        public string GeneratorName { get; set; }
        public System.DateTime Starts { get; set; }
        public double Every { get; set; }
        public string ReminderLevel { get; set; }
        public string Authoriser { get; set; }
        public double ReminderHoursProfile { get; set; }
        public System.DateTime ReminderDateTimeProfile { get; set; }
        public string IsActive { get; set; }
        public string IsRepetitive { get; set; }
    }
}
