//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeneratorSurveillanceDBEntities : DbContext
    {
        public GeneratorSurveillanceDBEntities()
            : base("name=GeneratorSurveillanceDBEntities"){ }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionPartySetting> ActionPartySettings { get; set; }
        public virtual DbSet<AuthoriserSetting> AuthoriserSettings { get; set; }
        public virtual DbSet<ConsumptionSetting> ConsumptionSettings { get; set; }
        public virtual DbSet<GeneratorFuelling> GeneratorFuellings { get; set; }
        public virtual DbSet<GeneratorMaintenance> GeneratorMaintenances { get; set; }
        public virtual DbSet<GeneratorRunningHr> GeneratorRunningHrs { get; set; }
        public virtual DbSet<GeneratorScheduler> GeneratorSchedulers { get; set; }
        public virtual DbSet<GeneratorUsage> GeneratorUsages { get; set; }
        public virtual DbSet<Password> Passwords { get; set; }
    }
}
