//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratorRunningHr
    {
        public int Id { get; set; }
        public string Generator { get; set; }
        public System.DateTime Date { get; set; }
        public double RunningHours { get; set; }
        public double CumFuelVolumeSinceLastReading { get; set; }
        public int SN { get; set; }
    }
}
